

// MOCK CLIENT-SIDE API
// In a real application, this would make network requests to a backend.

// The shape of the successful response from the (simulated) server
interface AuthSuccess {
    activationToken: string;
    permanentID: string;
}

/**
 * Simulates the initial handshake to get an activation token.
 * In a real app, this would check localStorage for a token, validate it with a server,
 * or guide the user through a login/payment flow.
 *
 * For this demo, we'll simulate a user who has already paid.
 */
export const initSystemHandshake = (): Promise<AuthSuccess> => {
    console.log("[MOCK_API] Initiating system handshake...");

    return new Promise((resolve, reject) => {
        setTimeout(() => {
            // First, check if a token already exists from a previous session
            const existingToken = localStorage.getItem('OMNI_ACTIVATION_TOKEN');
            const existingId = localStorage.getItem('OMNI_LIFETIME_ID');

            if (existingToken && existingId) {
                console.log("[MOCK_API] Found existing session token. Granting access.");
                resolve({
                    activationToken: existingToken,
                    permanentID: existingId,
                });
                return;
            }

            // If no token, we simulate a "first-time" successful login.
            // In a real app, you'd be coming from a successful payment page
            // or a login form. Here, we just grant access directly for demo purposes.
            console.log("[MOCK_API] No session found. Simulating successful first-time activation.");

            // This is a fake JWT. In a real app, it would be generated by a server
            // and signed with a secret key.
            const fakeJwt = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.${btoa(JSON.stringify({ user: 'demo_user', access: 'LIFETIME', iat: Date.now() }))}.${btoa('mock_signature')}`;
            
            // This is a simulated permanent ID, like a Stripe Customer ID.
            const permanentId = `cus_sim_${Date.now().toString(36)}`;

            resolve({
                activationToken: fakeJwt,
                permanentID: permanentId,
            });

        }, 1500); // Simulate network delay
    });
};


/**
 * Simulates restoring a session using a permanent ID.
 */
export const restoreSession = (permanentID: string): Promise<AuthSuccess> => {
    console.log(`[MOCK_API] Attempting to restore session for ID: ${permanentID}`);
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            if (permanentID && permanentID.startsWith('cus_sim_')) {
                 console.log("[MOCK_API] Restore successful. Generating new token.");
                 const fakeJwt = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.${btoa(JSON.stringify({ user: 'restored_user', access: 'LIFETIME', iat: Date.now() }))}.${btoa('mock_signature')}`;
                 resolve({
                    activationToken: fakeJwt,
                    permanentID: permanentID,
                });
            } else {
                console.error("[MOCK_API] Restore failed: Invalid ID format.");
                reject(new Error("Invalid or unrecognized Lifetime Credential."));
            }
        }, 1000);
    });
};

/**
 * Simulates the server-side verification of a Stripe payment session.
 */
export const verifyPaymentSimulation = (sessionId: string, customerId: string): Promise<AuthSuccess> => {
     console.log(`[MOCK_API] Verifying payment for session: ${sessionId}`);
     return new Promise((resolve, reject) => {
        setTimeout(() => {
            if (sessionId === 'chk_sim_123456789' && customerId === 'cus_sim_987654321') {
                console.log("[MOCK_API] Payment verification successful.");
                const fakeJwt = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.${btoa(JSON.stringify({ user: 'new_customer', access: 'LIFETIME', iat: Date.now() }))}.${btoa('mock_signature')}`;
                
                // The customerId is the permanent ID
                resolve({
                    activationToken: fakeJwt,
                    permanentID: customerId, 
                });
            } else {
                 console.error("[MOCK_API] Payment verification failed: Invalid session details.");
                 reject(new Error("Could not verify payment session."));
            }
        }, 1200);
     });
};
